name: Anders Hafreager Test Function Deploy
description: Deploy a Cognite Function
inputs:
  cdf_project:
    description: The name of your cdf project
    required: true
  cdf_credentials:
    description: CDF api key that's used to deploy the function
    required: true
  cdf_base_url:
    description: Base url of your cdf project
    default: https://api.cognitedata.com
    required: false
  function_path:
    description: Path to the directory containing the Python function
    required: false
    default: example
outputs:
  functionId: # id of output
    description: The ID of the function output. Use this to do calls against the API!
runs:
  using: 'docker'
  image: Dockerfile
