name: Anders Hafreager Test Function Deploy
description: Deploy a Cognite Function
inputs:
  cdf_project:
    description: The name of your cdf project
    required: true
  cdf_deployment_credentials:
    description: CDF API key that's provided to the deployed function
    required: true
  cdf_function_credentials:
    description: CDF API key that's used for deployment
    required: false
  cdf_base_url:
    description: Base url of your cdf project
    default: https://api.cognitedata.com
    required: false
  function_path:
    description: Path to the directory containing the Python function
    required: true
outputs:
  functionId: # id of output
    description: The ID of the function output. Use this to do calls against the API!
runs:
  using: 'docker'
  image: Dockerfile
